/*
 * Generated by breeze-generator (https://github.com/weibreeze/breeze-generator)
 * Schema: testmsg.breeze
 * Date: 2019/6/6
 */
package com.weibo.breeze.test.message;

import com.weibo.breeze.*;
import com.weibo.breeze.message.Message;
import com.weibo.breeze.message.Schema;

import java.lang.reflect.Type;
import java.util.*;

public class TestSubMsg implements Message {
    private static final Schema schema = new Schema();
    private static final Map<String, Type> genericTypes = new HashMap<>();
    private String myString;
    private int myInt;
    private long myInt64;
    private float myFloat32;
    private double myFloat64;
    private byte myByte;
    private byte[] myBytes;
    private Map<String, byte[]> myMap1;
    private Map<Integer, List<Integer>> myMap2;
    private List<Integer> myArray;
    private boolean myBool;

    static {
        try {
            schema.setName("motan.TestSubMsg")
                    .putField(new Schema.Field(1, "myString", "string"))
                    .putField(new Schema.Field(2, "myInt", "int32"))
                    .putField(new Schema.Field(3, "myInt64", "int64"))
                    .putField(new Schema.Field(4, "myFloat32", "float32"))
                    .putField(new Schema.Field(5, "myFloat64", "float64"))
                    .putField(new Schema.Field(6, "myByte", "byte"))
                    .putField(new Schema.Field(7, "myBytes", "bytes"))
                    .putField(new Schema.Field(8, "myMap1", "map<string, bytes>"))
                    .putField(new Schema.Field(9, "myMap2", "map<int32, array<int32>>"))
                    .putField(new Schema.Field(10, "myArray", "array<int32>"))
                    .putField(new Schema.Field(11, "myBool", "bool"));
        } catch (BreezeException ignore) {}
        Breeze.putMessageInstance(schema.getName(), new TestSubMsg());
        Breeze.addGenericType(genericTypes, TestSubMsg.class, "myMap1");
        Breeze.addGenericType(genericTypes, TestSubMsg.class, "myMap2");
        Breeze.addGenericType(genericTypes, TestSubMsg.class, "myArray");
    }

    @Override
    public void writeToBuf(BreezeBuffer buffer) throws BreezeException {
        BreezeWriter.writeMessage(buffer, schema.getName(), () -> {
            BreezeWriter.writeMessageField(buffer, 1, myString);
            BreezeWriter.writeMessageField(buffer, 2, myInt);
            BreezeWriter.writeMessageField(buffer, 3, myInt64);
            BreezeWriter.writeMessageField(buffer, 4, myFloat32);
            BreezeWriter.writeMessageField(buffer, 5, myFloat64);
            BreezeWriter.writeMessageField(buffer, 6, myByte);
            BreezeWriter.writeMessageField(buffer, 7, myBytes);
            BreezeWriter.writeMessageField(buffer, 8, myMap1);
            BreezeWriter.writeMessageField(buffer, 9, myMap2);
            BreezeWriter.writeMessageField(buffer, 10, myArray);
            BreezeWriter.writeMessageField(buffer, 11, myBool);
        });
    }

    @Override
    public Message readFromBuf(BreezeBuffer buffer) throws BreezeException {
        BreezeReader.readMessage(buffer, false, (int index) -> {
            switch (index) {
                case 1:
                    myString = BreezeReader.readObject(buffer, String.class);
                    break;
                case 2:
                    myInt = BreezeReader.readObject(buffer, int.class);
                    break;
                case 3:
                    myInt64 = BreezeReader.readObject(buffer, long.class);
                    break;
                case 4:
                    myFloat32 = BreezeReader.readObject(buffer, float.class);
                    break;
                case 5:
                    myFloat64 = BreezeReader.readObject(buffer, double.class);
                    break;
                case 6:
                    myByte = BreezeReader.readObject(buffer, byte.class);
                    break;
                case 7:
                    myBytes = BreezeReader.readObject(buffer, byte[].class);
                    break;
                case 8:
                    myMap1 = new HashMap<>();
                    BreezeReader.readMapByType(buffer, myMap1, genericTypes.get("myMap1" + Breeze.KEY_TYPE_SUFFIX), genericTypes.get("myMap1" + Breeze.VALUE_TYPE_SUFFIX));
                    break;
                case 9:
                    myMap2 = new HashMap<>();
                    BreezeReader.readMapByType(buffer, myMap2, genericTypes.get("myMap2" + Breeze.KEY_TYPE_SUFFIX), genericTypes.get("myMap2" + Breeze.VALUE_TYPE_SUFFIX));
                    break;
                case 10:
                    myArray = new ArrayList<>();
                    BreezeReader.readCollectionByType(buffer, myArray, genericTypes.get("myArray" + Breeze.VALUE_TYPE_SUFFIX));
                    break;
                case 11:
                    myBool = BreezeReader.readObject(buffer, boolean.class);
                    break;
                default: //skip unknown field
                    BreezeReader.readObject(buffer, Object.class);
            }
        });
        return this;
    }

    @Override
    public String getName() { return schema.getName(); }

    @Override
    public String getAlias() { return schema.getAlias(); }

    @Override
    public Schema getSchema() { return schema; }

    @Override
    public Message getDefaultInstance() { return new TestSubMsg(); }

    public String getMyString() { return myString; }

    public void setMyString(String myString) { this.myString = myString; }

    public int getMyInt() { return myInt; }

    public void setMyInt(int myInt) { this.myInt = myInt; }

    public long getMyInt64() { return myInt64; }

    public void setMyInt64(long myInt64) { this.myInt64 = myInt64; }

    public float getMyFloat32() { return myFloat32; }

    public void setMyFloat32(float myFloat32) { this.myFloat32 = myFloat32; }

    public double getMyFloat64() { return myFloat64; }

    public void setMyFloat64(double myFloat64) { this.myFloat64 = myFloat64; }

    public byte getMyByte() { return myByte; }

    public void setMyByte(byte myByte) { this.myByte = myByte; }

    public byte[] getMyBytes() { return myBytes; }

    public void setMyBytes(byte[] myBytes) { this.myBytes = myBytes; }

    public Map<String, byte[]> getMyMap1() { return myMap1; }

    public void setMyMap1(Map<String, byte[]> myMap1) { this.myMap1 = myMap1; }

    public Map<Integer, List<Integer>> getMyMap2() { return myMap2; }

    public void setMyMap2(Map<Integer, List<Integer>> myMap2) { this.myMap2 = myMap2; }

    public List<Integer> getMyArray() { return myArray; }

    public void setMyArray(List<Integer> myArray) { this.myArray = myArray; }

    public boolean getMyBool() { return myBool; }

    public void setMyBool(boolean myBool) { this.myBool = myBool; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TestSubMsg that = (TestSubMsg) o;

        if (myInt != that.myInt) return false;
        if (myInt64 != that.myInt64) return false;
        if (Float.compare(that.myFloat32, myFloat32) != 0) return false;
        if (Double.compare(that.myFloat64, myFloat64) != 0) return false;
        if (myByte != that.myByte) return false;
        if (myBool != that.myBool) return false;
        if (myString != null ? !myString.equals(that.myString) : that.myString != null) return false;
        if (!Arrays.equals(myBytes, that.myBytes)) return false;
//        if (myMap1 != null ? !myMap1.equals(that.myMap1) : that.myMap1 != null) return false;
        if (myMap2 != null ? !myMap2.equals(that.myMap2) : that.myMap2 != null) return false;
        return myArray != null ? myArray.equals(that.myArray) : that.myArray == null;
    }

    @Override
    public int hashCode() {
        int result;
        long temp;
        result = myString != null ? myString.hashCode() : 0;
        result = 31 * result + myInt;
        result = 31 * result + (int) (myInt64 ^ (myInt64 >>> 32));
        result = 31 * result + (myFloat32 != +0.0f ? Float.floatToIntBits(myFloat32) : 0);
        temp = Double.doubleToLongBits(myFloat64);
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        result = 31 * result + (int) myByte;
        result = 31 * result + Arrays.hashCode(myBytes);
        result = 31 * result + (myMap1 != null ? myMap1.hashCode() : 0);
        result = 31 * result + (myMap2 != null ? myMap2.hashCode() : 0);
        result = 31 * result + (myArray != null ? myArray.hashCode() : 0);
        result = 31 * result + (myBool ? 1 : 0);
        return result;
    }
}
