// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.weibo.test.proto;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string address = 2;</code>
   */
  String getAddress();
  /**
   * <code>optional string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>map&lt;string, string&gt; other = 3;</code>
   */
  int getOtherCount();
  /**
   * <code>map&lt;string, string&gt; other = 3;</code>
   */
  boolean containsOther(
          String key);
  /**
   * Use {@link #getOtherMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getOther();
  /**
   * <code>map&lt;string, string&gt; other = 3;</code>
   */
  java.util.Map<String, String>
  getOtherMap();
  /**
   * <code>map&lt;string, string&gt; other = 3;</code>
   */

  String getOtherOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; other = 3;</code>
   */

  String getOtherOrThrow(
          String key);
}
