// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.weibo.test.proto;

/**
 * Protobuf type {@code proto.User}
 */
public  final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.User)
    UserOrBuilder {
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    name_ = "";
    age_ = 0;
    gender_ = 0;
    address_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            age_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            gender_ = rawValue;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              address_ = new java.util.ArrayList<Address>();
              mutable_bitField0_ |= 0x00000008;
            }
            address_.add(
                input.readMessage(Address.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        address_ = java.util.Collections.unmodifiableList(address_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.weibo.test.proto.UserProto.internal_static_proto_User_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.weibo.test.proto.UserProto.internal_static_proto_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            User.class, Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile Object name_;
  /**
   * <code>optional string name = 1;</code>
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <code>optional int32 age = 2;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int GENDER_FIELD_NUMBER = 3;
  private int gender_;
  /**
   * <code>optional .proto.Gender gender = 3;</code>
   */
  public int getGenderValue() {
    return gender_;
  }
  /**
   * <code>optional .proto.Gender gender = 3;</code>
   */
  public Gender getGender() {
    Gender result = Gender.valueOf(gender_);
    return result == null ? Gender.UNRECOGNIZED : result;
  }

  public static final int ADDRESS_FIELD_NUMBER = 4;
  private java.util.List<Address> address_;
  /**
   * <code>repeated .proto.Address address = 4;</code>
   */
  public java.util.List<Address> getAddressList() {
    return address_;
  }
  /**
   * <code>repeated .proto.Address address = 4;</code>
   */
  public java.util.List<? extends AddressOrBuilder>
      getAddressOrBuilderList() {
    return address_;
  }
  /**
   * <code>repeated .proto.Address address = 4;</code>
   */
  public int getAddressCount() {
    return address_.size();
  }
  /**
   * <code>repeated .proto.Address address = 4;</code>
   */
  public Address getAddress(int index) {
    return address_.get(index);
  }
  /**
   * <code>repeated .proto.Address address = 4;</code>
   */
  public AddressOrBuilder getAddressOrBuilder(
      int index) {
    return address_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (gender_ != Gender.Man.getNumber()) {
      output.writeEnum(3, gender_);
    }
    for (int i = 0; i < address_.size(); i++) {
      output.writeMessage(4, address_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (gender_ != Gender.Man.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, gender_);
    }
    for (int i = 0; i < address_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, address_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof User)) {
      return super.equals(obj);
    }
    User other = (User) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (getAge()
        == other.getAge());
    result = result && gender_ == other.gender_;
    result = result && getAddressList()
        .equals(other.getAddressList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + gender_;
    if (getAddressCount() > 0) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddressList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.User)
      com.weibo.test.proto.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weibo.test.proto.UserProto.internal_static_proto_User_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weibo.test.proto.UserProto.internal_static_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              User.class, Builder.class);
    }

    // Construct using com.weibo.test.proto.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      age_ = 0;

      gender_ = 0;

      if (addressBuilder_ == null) {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        addressBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.weibo.test.proto.UserProto.internal_static_proto_User_descriptor;
    }

    public User getDefaultInstanceForType() {
      return User.getDefaultInstance();
    }

    public User build() {
      User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public User buildPartial() {
      User result = new User(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.age_ = age_;
      result.gender_ = gender_;
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = java.util.Collections.unmodifiableList(address_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof User) {
        return mergeFrom((User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(User other) {
      if (other == User.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.gender_ != 0) {
        setGenderValue(other.getGenderValue());
      }
      if (addressBuilder_ == null) {
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
      } else {
        if (!other.address_.isEmpty()) {
          if (addressBuilder_.isEmpty()) {
            addressBuilder_.dispose();
            addressBuilder_ = null;
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000008);
            addressBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAddressFieldBuilder() : null;
          } else {
            addressBuilder_.addAllMessages(other.address_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private int gender_ = 0;
    /**
     * <code>optional .proto.Gender gender = 3;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>optional .proto.Gender gender = 3;</code>
     */
    public Builder setGenderValue(int value) {
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.Gender gender = 3;</code>
     */
    public Gender getGender() {
      Gender result = Gender.valueOf(gender_);
      return result == null ? Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .proto.Gender gender = 3;</code>
     */
    public Builder setGender(Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .proto.Gender gender = 3;</code>
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<Address> address_ =
      java.util.Collections.emptyList();
    private void ensureAddressIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        address_ = new java.util.ArrayList<Address>(address_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Address, Address.Builder, AddressOrBuilder> addressBuilder_;

    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public java.util.List<Address> getAddressList() {
      if (addressBuilder_ == null) {
        return java.util.Collections.unmodifiableList(address_);
      } else {
        return addressBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public int getAddressCount() {
      if (addressBuilder_ == null) {
        return address_.size();
      } else {
        return addressBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Address getAddress(int index) {
      if (addressBuilder_ == null) {
        return address_.get(index);
      } else {
        return addressBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder setAddress(
        int index, Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
      } else {
        addressBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder setAddress(
        int index, Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.set(index, builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder addAddress(Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
      } else {
        addressBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder addAddress(
        int index, Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.add(index, value);
        onChanged();
      } else {
        addressBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder addAddress(
        Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.add(builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder addAddress(
        int index, Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.add(index, builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder addAllAddress(
        Iterable<? extends Address> values) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
      } else {
        addressBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        addressBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Builder removeAddress(int index) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.remove(index);
        onChanged();
      } else {
        addressBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Address.Builder getAddressBuilder(
        int index) {
      return getAddressFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public AddressOrBuilder getAddressOrBuilder(
        int index) {
      if (addressBuilder_ == null) {
        return address_.get(index);  } else {
        return addressBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public java.util.List<? extends AddressOrBuilder>
         getAddressOrBuilderList() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(address_);
      }
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Address.Builder addAddressBuilder() {
      return getAddressFieldBuilder().addBuilder(
          Address.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public Address.Builder addAddressBuilder(
        int index) {
      return getAddressFieldBuilder().addBuilder(
          index, Address.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Address address = 4;</code>
     */
    public java.util.List<Address.Builder>
         getAddressBuilderList() {
      return getAddressFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Address, Address.Builder, AddressOrBuilder>
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Address, Address.Builder, AddressOrBuilder>(
                address_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:proto.User)
  }

  // @@protoc_insertion_point(class_scope:proto.User)
  private static final User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new User();
  }

  public static User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  public User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

